env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod download
builds:
  -
    id: "docker-debug"
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: docker-execroot

    github:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/docker-execroot"

    # Your app's description.
    # Default is empty.
    description: "Sandstorm Docker Debug Tools"

    # see https://ruby-doc.org/stdlib-2.7.2/libdoc/fileutils/rdoc/index.html
    install: |
      mkdir_p File.expand_path('~') + "/.docker/cli-plugins/"
      ln_sf "#{prefix}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-execroot"
      ln_sf "#{prefix}/docker-execroot", File.expand_path('~') + "/.docker/cli-plugins/docker-vscode"